version: "3.9"

services:
  database:
    image: postgres
    container_name: postgres_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Hos32575@
      - POSTGRES_DB=teste-teddy-open-finence
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
